# TODO: Add a step to update the version number if needed
# TODO: Add a step to check correctness of the version number if needed

name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'release'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Delete release branch
      run: git push origin --delete release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
