name: Release Test

on:
   pull_request:
    types:
      - opened
      - synchronize
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build
    
    - name: Show Release Content
      run: npm pack --dry-run

    # - name: Publish to npm
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
